language: node_js

node_js:
    - "8"

sudo: required

script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run start &
  - sleep 1
  - xvfb-run npm run test-e2e
  - pkill node

#  - touch dist/.nojekyll
#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: dist/
#  github_token: $GITHUB_TOKEN
#  fqdn: fosdem.sojourner.rocks
#  keep_history: true
#  on:
#    branch: master
