language: node_js

node_js:
    - "8"

sudo: required

script:
  - npm run lint
  - npm run start &
  - sleep 10
  - npm run test
  - xvfb-run npm run test-e2e
  - pkill node
  - touch .nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
