language: node_js

node_js:
    - "8"

sudo: required

env:
  global:
    - CONFERENCE_ID=flowcon-2019
    - FIREBASE_API_KEY=AIzaSyDdGLMo8SACp-7E2g_HXaPs-0VWjBktRpA
    - FIREBASE_AUTH_DOMAIN=sojourer-web.firebaseapp.com
    - FIREBASE_DATABASE_URL=https://sojourer-web.firebaseio.com
    - FIREBASE_PROJECT_ID=sojourer-web
    - FIREBASE_STORAGE_BUCKET=sojourer-web.appspot.com
    - FIREBASE_MESSAGING_SENDER_ID=618264640987

script:
  - cp sample.env .env
  - npm run lint
  - npm run test
  - npm run build
  - npm run start &
  - sleep 1
  - xvfb-run npm run test-e2e
  - pkill node

#  - touch dist/.nojekyll
#deploy:
#  provider: pages
#  skip_cleanup: true
#  local_dir: dist/
#  github_token: $GITHUB_TOKEN
#  fqdn: fosdem.sojourner.rocks
#  keep_history: true
#  on:
#    branch: master
